/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package datamining.layout;

import datamining.classify.Classify;
import datamining.core.Instances;
import datamining.rough.AttributeReduction;
import datamining.rough.Discretization;
import datamining.rough.Util;
import datamining.rough.ValueReduction;
import datamining.util.PropertiesUtil;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lenovo
 */
public class RoughClassifyFrame extends javax.swing.JFrame {

    private Instances dataSet;
    private String tmpClassifierName;
    private Classify classifier;
    private Discretization discretization;
    private ValueReduction valueReduction;
    private String tmpDiscretizationName;
    private String tmpValueReductionName;
    private ProgressDialog dialog;
    private Instances inst;

    /**
     * Creates new form RoughClassifyFrame
     */
    public RoughClassifyFrame() {
        initComponents();
    }

    RoughClassifyFrame(Instances dataSet) {
        this.dataSet = dataSet;
        try {
            inst = (Instances) cloneObject(dataSet);
        } catch (IOException ex) {
            Logger.getLogger(RoughClassifyFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RoughClassifyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
//        tmpClassifierName = (String) jRclassifyComboBox.getSelectedItem();
//        classifier = PropertiesUtil.getClassifier(tmpClassifierName);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRdiscretization = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jRvaluereduction = new javax.swing.JComboBox();
        jDiscretizationButton = new javax.swing.JButton();
        jAttributeReductionButton = new javax.swing.JButton();
        jValueReductionButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("");

        jLabel2.setText("离散化数值：");

        jRdiscretization.setModel(new javax.swing.DefaultComboBoxModel(PropertiesUtil.getPropItems(PropertiesUtil.DISCRETIZATION)));

        jLabel3.setText("属性约简：");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AttributeReduction" }));

        jLabel4.setText("值约简：");

        jRvaluereduction.setModel(new javax.swing.DefaultComboBoxModel(PropertiesUtil.getPropItems(PropertiesUtil.VALUEREDUCTION)));

        jDiscretizationButton.setText("执行");
        jDiscretizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiscretizationButtonActionPerformed(evt);
            }
        });

        jAttributeReductionButton.setText("执行");
        jAttributeReductionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAttributeReductionButtonActionPerformed(evt);
            }
        });

        jValueReductionButton.setText("执行");
        jValueReductionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValueReductionButtonActionPerformed(evt);
            }
        });

        jButton5.setText("查看");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("分类器调用");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jValueReductionButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAttributeReductionButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDiscretizationButton, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRdiscretization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRvaluereduction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(jButton5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRdiscretization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiscretizationButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAttributeReductionButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRvaluereduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValueReductionButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("预处理", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDiscretizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiscretizationButtonActionPerformed
        // TODO add your handling code here:
        dialog = new ProgressDialog(this, false);
        dialog.setPoint("数据处理中...");
        dialog.setVisible(true);
        new Thread(new Runnable() {

            @Override
            public void run() {
                tmpDiscretizationName = (String) jRdiscretization.getSelectedItem();
                discretization = PropertiesUtil.getDiscretization(tmpDiscretizationName);
                inst = discretization.getDiscretizationInstances(inst, discretization.discrete(inst));
//                for (int i = 0; i < dataSet.numInstances(); i++) {
//                    for (int j = 0; j < dataSet.numAttributes(); j++) {
//                        System.out.print(dataSet.instance(i).value(j) + "\t");
//                    }
//                    System.out.print("\n");
//                }
                dialog.dispose();
            }
        }).start();

    }//GEN-LAST:event_jDiscretizationButtonActionPerformed

    private void jValueReductionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValueReductionButtonActionPerformed
        // TODO add your handling code here:
        dialog = new ProgressDialog(this, false);
        dialog.setPoint("数据处理中...");
        dialog.setVisible(true);
        new Thread(new Runnable() {

            @Override
            public void run() {
                tmpValueReductionName = (String) jRvaluereduction.getSelectedItem();
                valueReduction = PropertiesUtil.getValueReduction(tmpValueReductionName);
                inst = valueReduction.GetReducedInstances(inst);
                dialog.dispose();
            }
        }).start();

    }//GEN-LAST:event_jValueReductionButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArffFileViewer arffFileViewer = new ArffFileViewer(inst, null);
        arffFileViewer.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jAttributeReductionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAttributeReductionButtonActionPerformed
        // TODO add your handling code here:
        dialog = new ProgressDialog(this, false);
        dialog.setPoint("数据处理中...");
        dialog.setVisible(true);
        new Thread(new Runnable() {

            @Override
            public void run() {
                int[] index;
                AttributeReduction ar = new AttributeReduction();
                index = ar.reductionByAttributeOrder(inst);
                try {
                    inst = Util.ReduceInstances(inst, index);
                } catch (Exception ex) {
                    Logger.getLogger(RoughClassifyFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.dispose();
            }
        }).start();
    }//GEN-LAST:event_jAttributeReductionButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClassifyFrame classifyFrame = new ClassifyFrame(inst);
        classifyFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private Object cloneObject(Object obj) throws IOException, ClassNotFoundException {
        ObjectOutputStream out;
        ByteArrayInputStream byteIn;
        ObjectInputStream in;
        Object object;

        ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
        out = new ObjectOutputStream(byteOut);
        out.writeObject(obj);
        byteIn = new ByteArrayInputStream(byteOut.toByteArray());
        in = new ObjectInputStream(byteIn);
        object = in.readObject();
        out.close();
        in.close();
        return object;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoughClassifyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoughClassifyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoughClassifyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoughClassifyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RoughClassifyFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAttributeReductionButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JButton jDiscretizationButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jRdiscretization;
    private javax.swing.JComboBox jRvaluereduction;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jValueReductionButton;
    // End of variables declaration//GEN-END:variables
}
